name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run all scripts in one step
        run: |
          echo Hello, world!
          echo Add other actions to build,
          echo test, and deploy your project.
